apiVersion: v1
kind: Service
metadata:
  name: addressbookbalancer
  labels:
    service: addressbookloadbalancer
spec:
  selector:
    app: addressbook 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31010
    targetPort: 8080
