apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    service: my-service
spec:
  selector:
    app: my-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    nodePort: 32222 

