apiVersion: v1
kind: Service
metadata:
  name: my-serviceloadbalancer
  labels:
    service: my-serviceloadbalancer
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31000
